# Generated by Django 4.2 on 2024-07-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=30)),
                ('director', models.CharField(max_length=40)),
                ('year', models.IntegerField()),
                ('sinopsis', models.TextField()),
            ],
        ),
    ]
